spring:
  application:
    name: accountservice

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DATABASE:Bankingsystem}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  cloud:
    inetutils:
      preferred-networks:
        - 127

      ignored-interfaces:
        - eth.*
        - docker.*
        - veth.*
        - br.*



# SERVER (HTTPS)
server:
  port: 8901
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: bankingapp
auth:
  service:
    base-url: http://AUTHSERVICE
# EUREKA
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

  instance:
    prefer-ip-address: false
    non-secure-port-enabled: false
    secure-port-enabled: true
    hostname: localhost
    ip-address: 127.0.0.1
    secure-port: 8901
    instance-id: ${spring.application.name}:${server.port}
# LOGGING
logging:
  level:
    root: DEBUG
